// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524112530_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 24, 9, 30, 0, 0, DateTimeKind.Utc),
                            Text = "Hata tekrar uretildi, loglar inceleniyor.",
                            TicketId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 24, 11, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Excel export icin gerekli alanlar belirlendi.",
                            TicketId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 24, 16, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Sorgu optimizasyonu sonrasi performans iyilesti.",
                            TicketId = 4
                        });
                });

            modelBuilder.Entity("backend.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedToId = 1,
                            CreatedAt = new DateTime(2026, 5, 24, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kullanici dogru sifre ile giris yapmasina ragmen hata aliyor.",
                            Priority = "High",
                            Status = "Open",
                            Title = "Login ekraninda hata"
                        },
                        new
                        {
                            Id = 2,
                            AssignedToId = 2,
                            CreatedAt = new DateTime(2026, 5, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Aylik talep raporlarinin Excel olarak indirilebilmesi gerekiyor.",
                            Priority = "Medium",
                            Status = "In Progress",
                            Title = "Rapor disari aktarma istegi",
                            UpdatedAt = new DateTime(2026, 5, 24, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AssignedToId = 3,
                            CreatedAt = new DateTime(2026, 5, 24, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yeni talep acildiginda sorumlu kullaniciya e-posta ulasmiyor.",
                            Priority = "High",
                            Status = "Open",
                            Title = "Bildirim e-postalari gelmiyor"
                        },
                        new
                        {
                            Id = 4,
                            AssignedToId = 1,
                            CreatedAt = new DateTime(2026, 5, 24, 13, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Profil detaylari yuklenirken bekleme suresi cok uzun.",
                            Priority = "Low",
                            Status = "Resolved",
                            Title = "Profil sayfasi yavas aciliyor",
                            UpdatedAt = new DateTime(2026, 5, 24, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 24, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Destek talepleri icin kategori secimi eklenmesi isteniyor.",
                            Priority = "Medium",
                            Status = "Open",
                            Title = "Yeni kategori ekleme"
                        });
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ayse.demir@example.com",
                            FullName = "Ayse Demir"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mehmet.yilmaz@example.com",
                            FullName = "Mehmet Yilmaz"
                        },
                        new
                        {
                            Id = 3,
                            Email = "zeynep.kaya@example.com",
                            FullName = "Zeynep Kaya"
                        });
                });

            modelBuilder.Entity("backend.Models.Comment", b =>
                {
                    b.HasOne("backend.Models.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("backend.Models.Ticket", b =>
                {
                    b.HasOne("backend.Models.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedTo");
                });

            modelBuilder.Entity("backend.Models.Ticket", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
